/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;

import dao.UsuarioDao;
import modelo.Usuarios;

/**
 *
 * @author isaqu
 */
public class Login extends javax.swing.JFrame {

    

     
    private UsuarioDao usuarioDao = new UsuarioDao();
    Color panDefault, panEnter, panClick;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        panDefault = new Color(220,141,77);
        panClick = new Color(223,171,87);
        panEnter = new Color(234,98,43);
        jPanLogin.setBackground(panDefault);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLCadastrar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        senhaField = new javax.swing.JPasswordField();
        jPanLogin = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(13, 36, 70));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(13, 36, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(220, 141, 77));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 170, 75));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuário-96.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 470));

        jLCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jLCadastrar.setText("Não tem uma conta ainda?");
        jLCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLCadastrarMouseExited(evt);
            }
        });
        jPanel1.add(jLCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 190, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 330, -1));

        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 330, -1));

        nomeField.setBackground(new java.awt.Color(13, 36, 70));
        nomeField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nomeField.setForeground(new java.awt.Color(255, 255, 255));
        nomeField.setBorder(null);
        jPanel1.add(nomeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 330, 40));

        senhaField.setBackground(new java.awt.Color(13, 36, 70));
        senhaField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        senhaField.setForeground(new java.awt.Color(255, 255, 255));
        senhaField.setBorder(null);
        jPanel1.add(senhaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 330, 40));

        jPanLogin.setBackground(new java.awt.Color(220, 141, 77));
        jPanLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanLoginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanLoginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanLoginMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login");

        javax.swing.GroupLayout jPanLoginLayout = new javax.swing.GroupLayout(jPanLogin);
        jPanLogin.setLayout(jPanLoginLayout);
        jPanLoginLayout.setHorizontalGroup(
            jPanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(jPanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanLoginLayout.setVerticalGroup(
            jPanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanLoginLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 240, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Senha");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 465));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanLoginMouseEntered
        // TODO add your handling code here:
        jPanLogin.setBackground(panEnter);
        
    }//GEN-LAST:event_jPanLoginMouseEntered

    private void jPanLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanLoginMouseExited
        // TODO add your handling code here:
        jPanLogin.setBackground(panDefault);
    }//GEN-LAST:event_jPanLoginMouseExited

    private void jPanLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanLoginMousePressed
        // TODO add your handling code here:
        jPanLogin.setBackground(panClick);
    }//GEN-LAST:event_jPanLoginMousePressed

    private void jPanLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanLoginMouseReleased
        // TODO add your handling code here:
        jPanLogin.setBackground(panDefault);
    }//GEN-LAST:event_jPanLoginMouseReleased

    private void jLCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCadastrarMouseEntered
        // TODO add your handling code here:
        jLCadastrar.setForeground(new Color(12,72,186));
    }//GEN-LAST:event_jLCadastrarMouseEntered

    private void jLCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCadastrarMouseExited
        // TODO add your handling code here:
        jLCadastrar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_jLCadastrarMouseExited

    private void jPanLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanLoginMouseClicked
        // TODO add your handling code here:
        Usuarios usuario = new Usuarios();
        usuario.setNome(nomeField.getText());
        usuario.setSenha(senhaField.getPassword(),true);
        if(usuarioDao.logar(usuario)){
            Dashboard dashboard = new Dashboard(usuario);
            dashboard.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jPanLoginMouseClicked

    private void jLCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCadastrarMouseClicked
        // TODO add your handling code here:
        GetUser getUser = new GetUser();
        getUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLCadastrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nomeField;
    private javax.swing.JPasswordField senhaField;
    // End of variables declaration//GEN-END:variables
}
