/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package gui;

import dao.DailyDao;
import dao.UsuarioDao;
import java.awt.Color;
import java.sql.Date;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import modelo.Daily;
import modelo.Usuarios;

/**
 *
 * @author isaqu
 */
public class MostrarDailys extends javax.swing.JInternalFrame {

    /**
     * Creates new form FazerDaily
     */
    
    private Usuarios usuario = new Usuarios();
    private UsuarioDao usuarioDao = new UsuarioDao();
    private DailyDao dailyDao = new DailyDao();
    
    
    public MostrarDailys() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }
    
    public MostrarDailys(int id) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        this.usuario.setId(id);
        this.usuario = this.usuarioDao.getUsuarioById(usuario.getId());
        listarValores(usuario.getId());
        if(!this.usuario.getCargo().equals("Scrum Master")){
        scrumButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaDaily = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        atualizarTabela = new javax.swing.JButton();
        scrumButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextCargo = new javax.swing.JTextField();
        jTextName1 = new javax.swing.JTextField();
        jTextData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jConteudo = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        salvarAlteracao = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(920, 600));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(920, 591));

        tabelaDaily.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 36, 70)));
        tabelaDaily.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tabelaDaily.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Cargo", "Data Realizada", "Conteudo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDaily.setPreferredSize(new java.awt.Dimension(920, 591));
        tabelaDaily.setRowHeight(50);
        tabelaDaily.setSelectionBackground(new java.awt.Color(220, 141, 77));
        tabelaDaily.setSelectionForeground(new java.awt.Color(13, 36, 70));
        tabelaDaily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDailyMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaDailyMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaDaily);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 36, 70)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Data Realizada:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 40));

        atualizarTabela.setBackground(new java.awt.Color(13, 36, 70));
        atualizarTabela.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        atualizarTabela.setForeground(new java.awt.Color(255, 255, 255));
        atualizarTabela.setText("Atualizar tabela");
        atualizarTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atualizarTabelaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atualizarTabelaMouseExited(evt);
            }
        });
        atualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarTabelaActionPerformed(evt);
            }
        });
        jPanel1.add(atualizarTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        scrumButton.setBackground(new java.awt.Color(13, 36, 70));
        scrumButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        scrumButton.setForeground(new java.awt.Color(255, 255, 255));
        scrumButton.setText("Ver todas as daily");
        scrumButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scrumButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                scrumButtonMouseExited(evt);
            }
        });
        scrumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scrumButtonActionPerformed(evt);
            }
        });
        jPanel1.add(scrumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Conteudo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nome: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Conteudo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cargo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 40));

        jTextCargo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCargoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 290, 40));

        jTextName1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextName1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 290, 40));

        jTextData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDataActionPerformed(evt);
            }
        });
        jPanel1.add(jTextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 230, 40));

        jConteudo.setColumns(20);
        jConteudo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jConteudo.setLineWrap(true);
        jConteudo.setRows(5);
        jScrollPane1.setViewportView(jConteudo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 390, 240));

        jButton1.setBackground(new java.awt.Color(13, 36, 70));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Deletar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, -1, -1));

        salvarAlteracao.setBackground(new java.awt.Color(13, 36, 70));
        salvarAlteracao.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        salvarAlteracao.setForeground(new java.awt.Color(255, 255, 255));
        salvarAlteracao.setText("Salvar alterções");
        salvarAlteracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salvarAlteracaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salvarAlteracaoMouseExited(evt);
            }
        });
        salvarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarAlteracaoActionPerformed(evt);
            }
        });
        jPanel1.add(salvarAlteracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(381, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarTabelaActionPerformed
        // TODO add your handling code here:
        listarValores(usuario.getId());
    }//GEN-LAST:event_atualizarTabelaActionPerformed

    private void scrumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scrumButtonActionPerformed
        // TODO add your handling code here:
        listarValores();
    }//GEN-LAST:event_scrumButtonActionPerformed

    private void tabelaDailyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDailyMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabelaDailyMousePressed

    private void jTextCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCargoActionPerformed

    private void jTextName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextName1ActionPerformed

    private void jTextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDataActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Você tem certeza que quer deletar essa daily?","Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response==JOptionPane.YES_NO_OPTION) {
            
            DefaultTableModel model = (DefaultTableModel)tabelaDaily.getModel();
            int selectedRow=tabelaDaily.getSelectedRow();
            dailyDao.deletarDaily(Integer.parseInt(model.getValueAt(selectedRow, 0).toString()));
            listarValores(usuario.getId());
            
            
            

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salvarAlteracaoActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_salvarAlteracaoActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Você tem certeza que quer salvar as alterações?","Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response==JOptionPane.YES_NO_OPTION) {
            
            DefaultTableModel model = (DefaultTableModel)tabelaDaily.getModel();
            int selectedRow=tabelaDaily.getSelectedRow();
            String dataString = jTextData.getText();
            java.sql.Date data1 = Date.valueOf(dataString);
            Daily daily = new Daily();
            daily.setId(Integer.parseInt(model.getValueAt(selectedRow, 0).toString()));
            daily.setData(data1);
            daily.setConteudo(jConteudo.getText());
            dailyDao.alterarDaily(daily);
            listarValores(usuario.getId());
            
            

        }
    
    
    }//GEN-LAST:event_salvarAlteracaoActionPerformed

    private void salvarAlteracaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarAlteracaoMouseEntered
        // TODO add your handling code here:
        salvarAlteracao.setBackground(new Color(220,141,77));
    }//GEN-LAST:event_salvarAlteracaoMouseEntered

    private void salvarAlteracaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarAlteracaoMouseExited
        // TODO add your handling code here:
        salvarAlteracao.setBackground(new Color(13,36,70));
    }//GEN-LAST:event_salvarAlteracaoMouseExited

    private void atualizarTabelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarTabelaMouseEntered
        // TODO add your handling code here:
        atualizarTabela.setBackground(new Color(220,141,77));
    }//GEN-LAST:event_atualizarTabelaMouseEntered

    private void atualizarTabelaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizarTabelaMouseExited
        // TODO add your handling code here:
        atualizarTabela.setBackground(new Color(13,36,70));
    }//GEN-LAST:event_atualizarTabelaMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new Color(220,141,77));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(13,36,70));
    }//GEN-LAST:event_jButton1MouseExited

    private void scrumButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrumButtonMouseEntered
        // TODO add your handling code here:
        scrumButton.setBackground(new Color(220,141,77));
    }//GEN-LAST:event_scrumButtonMouseEntered

    private void scrumButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrumButtonMouseExited
        // TODO add your handling code here:
        scrumButton.setBackground(new Color(13,36,70));
    }//GEN-LAST:event_scrumButtonMouseExited

    private void tabelaDailyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDailyMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tabelaDaily.getModel();
        int selectedRow=tabelaDaily.getSelectedRow();
        jTextName1.setText(model.getValueAt(selectedRow, 1).toString());
        jTextCargo.setText(model.getValueAt(selectedRow, 2).toString());
        jTextData.setText(model.getValueAt(selectedRow, 3).toString());
        jConteudo.setText(model.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_tabelaDailyMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarTabela;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextArea jConteudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextCargo;
    private javax.swing.JTextField jTextData;
    private javax.swing.JTextField jTextName1;
    private javax.swing.JButton salvarAlteracao;
    private javax.swing.JButton scrumButton;
    private javax.swing.JTable tabelaDaily;
    // End of variables declaration//GEN-END:variables
    private void listarValores() {
        try {
            DailyDao objDailyDao =  new DailyDao();
            DefaultTableModel model = (DefaultTableModel) tabelaDaily.getModel();
            model.setNumRows(0);

            ArrayList<Daily> lista = objDailyDao.pesquisarDaily();
            for (int i = 0; i < lista.size(); i++) {
                model.addRow(new Object []{
                    lista.get(i).getId(),
                    lista.get(i).getNome(),
                    lista.get(i).getCargo(),
                    lista.get(i).getData(),
                    lista.get(i).getConteudo()
                });
            }

        } catch (Exception exception) {
            // TODO: handle exception
            throw new RuntimeException(exception);
        }
    }
    private void listarValores(int id) {
        try {
            DailyDao objDailyDao =  new DailyDao();
            DefaultTableModel model = (DefaultTableModel) tabelaDaily.getModel();
            model.setNumRows(0);

            ArrayList<Daily> lista = objDailyDao.pesquisarDaily(id);
            for (int i = 0; i < lista.size(); i++) {
                model.addRow(new Object []{
                    lista.get(i).getId(),
                    lista.get(i).getNome(),
                    lista.get(i).getCargo(),
                    lista.get(i).getData(),
                    lista.get(i).getConteudo()
                });
            }

        } catch (Exception exception) {
            // TODO: handle exception
            throw new RuntimeException(exception);
        }
    }




}
